name: CTDS_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.2.3
  - pandas=2.2.3
  - scikit-learn
  - networkx
  - ipykernel
  - pip
  - matplotlib
  - pip:
      - python-louvain
      - datasketch
      - faiss-cpu
